name: pytest-environment-setup

on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

jobs:
  # ref: https://github.com/marketplace/actions/setup-miniconda
  Ubuntu: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: l2d-vtb
          environment-file: environment.yml
          python-version: "3.7"
      - run: |
          conda env list
          conda activate l2d-vtb
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          conda install -c conda-forge dlib
          pip install scipy>0.16
          conda install pytorch==1.10.2 torchvision==0.11.3 torchaudio==0.10.2 cudatoolkit=10.2 -c pytorch
    
      - name: Run tests
        run: |
          pytest tests/test_linux.py


  MacOS:
    runs-on: macOS-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: l2d-vtb
          environment-file: environment.yml
          python-version: "3.7"
      - run: |
          conda env list
          conda activate l2d-vtb
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          conda install -c conda-forge dlib
          pip install scipy>0.16
          conda install pytorch==1.10.2 torchvision==0.11.3 torchaudio==0.10.2 -c pytorch
    
      - name: Run tests
        run: |
          pytest tests/test_mac.py
  

  Windows: 
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: l2d-vtb
          environment-file: environment.yml
          python-version: "3.7"
      - run: |
          conda env list
          conda activate l2d-vtb
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          conda install -c conda-forge dlib
          pip install scipy>0.16
          pip install torch==1.10.2+cu102 torchvision==0.11.3+cu102 torchaudio===0.10.2+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html
    
      - name: Run tests
        run: |
          pytest tests/test_win.py
